#!/usr/bin/env python
# -*- coding:utf-8 -*-

import sys

from pubs import pubs_cmd

try:
    pubs_cmd.execute()
except IOError:
    # stdout or stderr has been closed, cleaning up
    try:
        sys.stdout.close()
    except IOError:
        pass
    try:
        sys.stderr.close()
    except IOError:
        pass
